BB_CONF_FRAGMENT_SUMMARY = "Config specific overrides for arago-master-next-config"
BB_CONF_FRAGMENT_DESCRIPTION = "Config specific overrides for arago-master-next-config"

OVERRIDES:append = ":recipe-${@os.path.basename(d.getVar('FILE'))}"
BRANCH:recipe-linux-ti-staging_6.18.bb = "ti-linux-6.18.y-cicd"
BRANCH:recipe-linux-ti-staging-rt_6.18.bb = "ti-linux-6.18.y-cicd"
BRANCH:recipe-u-boot-ti-staging_2026.01.bb = "ti-u-boot-2026.01-next"
